[package]
name = "pyre"
version = "0.1.1"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "pyre"
crate-type = ["cdylib"]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3.git"
features = ["extension-module"]

[dependencies]
pyre-server = { version = "*", path = "pyre-server" }
pyre-framework = { version = "*", path = "pyre-framework" }


[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version="^0.3.2", features = ["disable_initial_exec_tls", "background_threads"] }

[profile.release]
lto = "fat"
codegen-units = 1
